### ISSUE TITLE
feat: finish milestone 2

### ISSUE THREAD

**Issue by peter-gy** [peter-gy/snip-man#19]
**Description**

The title should be pretty self-explanatory. The sole purpose of this issue is to act as a list with TODOs to be ticked off.

**Requirements**

- [x] Configuration of Infrastructure (6 points)
  - [x] IS container creation and composition (every service is deployable locally)
  - [x] Secure deployment (https, port exposure, data volumes, networks)
  - [x] Implement build-pipeline (everything build-related is done in Docker)
- [x] Logical/Physical database design (2 points)
  - [x] Relational model and normalization
  - [x] Implementation with relational DBMS
- [x]  Data import (2 points)
  - [x] Automated and randomized data creation for the SQL database
- [x] Implementation Web system (relational DBMS) (7 points)
- [x] Implementation of Use Cases (relational DBMS) (8 points)
  - [x] Realization of one main use case per team member (#17, #18)
  - [x] Realization of one report per team member (#21, #23)
- [x] NoSQL design decisions (15 points)
- [x] Data migration (2 points)
- [x] Implementation IS (NoSQL) (8 points)
